### ISSUE TITLE
Kanban board view

### ISSUE THREAD

**Issue by mglaman** [mglaman/drupalorg-issue-tracker#8]
As it stands the app is great right now for keeping track of issues of importance and performing clean up of a project as patches get committed, allowing their removal and projects to be updated. #7 references a filter to sort the list by the issues by their status.

It might be useful if this app could toggle into a kanban board. Provides a simpler way to manage personal contrib sprints.

**Comment by damienmckenna** [comment]
I couldn't imaging using it for a curated list, which is what it provides now, just because that's a lot of effort for only *one* list, you might as well use Trello.

Now, if it could automatically scrape an issue queue and let you control filtering of each category, that'd be amazing. Take a look at https://trello.com/b/rXe5zN5l/panelizer for an example of how I categorize everything on a project - the left-most items are simple lists of "backlog" items, as you move further right you find columns for specific releases, even subcategories for specific releases.

**Comment by mglaman** [comment]
I think I'm going to scrap this for my kanban app that'll be going up this month now that CORS is supported on the API.

**Comment by mglaman** [comment]
Closing this, because now we have http://contribkanban.com/!
